name: Build & Push

on:
  push:
    branches: [main]

env:
  IMAGE_PRODUCER: ghcr.io/${{ github.repository }}/producer
  IMAGE_CONSUMER: ghcr.io/${{ github.repository }}/consumer
  IMAGE_FLINK: ghcr.io/${{ github.repository }}/flink-transformation
  IMAGE_FLINK_SHADOW: ghcr.io/${{ github.repository }}/shadow-flink-transformation
  DOCKER_CLIENT_TIMEOUT: 300
  COMPOSE_HTTP_TIMEOUT: 300

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Build ONLY required modules (faster)
      - name: Build Producer
        run: mvn clean package -pl producer -am -DskipTests

      - name: Build Profile-Producer
        run: mvn clean package -pl profile-producer -am -DskipTests

      - name: Build Consumer
        run: mvn clean package -pl consumer -am -DskipTests

      - name: Build Flink Transformation
        run: mvn clean package -pl flink-transformation -am -DskipTests

      - name: Build Flink Transformation
        run: mvn clean package -pl shadow-flink-transformation -am -DskipTests

      # 4. Login to GHCR
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 5. Build & Push Producer
      - name: Build & Push Producer
        run: |
          docker build -t $IMAGE_PRODUCER:${{ github.sha }} ./producer
          docker push $IMAGE_PRODUCER:${{ github.sha }}

        # 5. Build & Push Profile Producer
      - name: Build & Push Profile-Producer
        run: |
          docker build -t $IMAGE_PROFILE_PRODUCER:${{ github.sha }} ./profile-producer
          docker push $IMAGE_PROFILE_PRODUCER:${{ github.sha }}

      # 6. Build & Push Consumer
      - name: Build & Push Consumer
        run: |
          docker build -t $IMAGE_CONSUMER:${{ github.sha }} ./consumer
          docker push $IMAGE_CONSUMER:${{ github.sha }}

      # 7. Build & Push Flink
      - name: Build & Push Flink
        run: |
          docker build -t $IMAGE_FLINK:${{ github.sha }} ./flink-transformation
          docker push $IMAGE_FLINK:${{ github.sha }}

      # 7. Build & Push Flink Shadow
      - name: Build & Push Shadow Flink Transformation
        run: |
          docker build -t $IMAGE_FLINK_SHADOW:${{ github.sha }} ./shadow-flink-transformation
          docker push $IMAGE_FLINK_SHADOW:${{ github.sha }}

      # 8. Clone deploy repo
      - name: Clone deploy repo
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/alexriley7/streaming-system-deploy.git

      # 9. Update image tags
      - name: Update deployment files
        run: |
          cd streaming-system-deploy

          sed -i "s|image:.*producer.*|image: $IMAGE_PRODUCER:${{ github.sha }}|" producer/producer-deployment.yaml
          sed -i "s|image:.*profile-producer.*|image: $IMAGE_PROFILE_PRODUCER:${{ github.sha }}|" profile-producer/profile-producer-deployment.yaml
          sed -i "s|image:.*consumer.*|image: $IMAGE_CONSUMER:${{ github.sha }}|" consumer/consumer-deployment.yaml
          sed -i "s|image:.*flink-transformation.*|image: $IMAGE_FLINK:${{ github.sha }}|" flink-transformation/flink-transformation-deployment.yaml
          sed -i "s|image:.*shadow-flink-transformation.*|image: $IMAGE_FLINK_SHADOW:${{ github.sha }}|" shadow-flink-transformation/shadow-flink-transformation-deployment.yaml

      # 10. Commit & push
      - name: Commit & Push
        run: |
          cd streaming-system-deploy

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "update images to ${{ github.sha }}" || echo "No changes"
          git push