name: Build & Push

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Build project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # 4. Login to GitHub Container Registry
      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # 5. Build Producer Image
      - name: Build Producer
        run: |
          docker build -t ghcr.io/${{ github.repository }}/producer:${{ github.sha }} ./producer

      # 6. Push Producer Image
      - name: Push Producer
        run: |
          docker push ghcr.io/${{ github.repository }}/producer:${{ github.sha }}

      # 7. Build Consumer Image
      - name: Build Consumer
        run: |
          docker build -t ghcr.io/${{ github.repository }}/consumer:${{ github.sha }} ./consumer

      # 8. Push Consumer Image
      - name: Push Consumer
        run: |
          docker push ghcr.io/${{ github.repository }}/consumer:${{ github.sha }}

      ### Update deploy repo
      #cd streaming-system-deploy

       
      - name: Update deploy repo
        run: |
          git clone https://github.com/alexriley7/streaming-system-deploy.git
          

          sed -i "s|image:.*producer.*|image: $IMAGE_PRODUCER:${{ github.sha }}|" producer-deployment.yaml
          sed -i "s|image:.*consumer.*|image: $IMAGE_CONSUMER:${{ github.sha }}|" consumer-deployment.yaml

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git commit -am "update images to ${{ github.sha }}"
          git push